---
# tasks file for PeterMosmans.customize-gnome

- name: Parse Gnome Shell version
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      gnome-shell --version | sed 's/^[^0-9.]*//' | sed 's/[^0-9]*$//'
    executable: /bin/bash
  register: r_gnome_extension_parse_shell_version
  changed_when: false

- name: Set Gnome Shell version as parameter
  ansible.builtin.set_fact:
    gnome_shell_version: "{{ r_gnome_extension_parse_shell_version.stdout }}"

# Abort early when no GNOME Shell is present.
- name: Ensure GNOME Shell is available
  ansible.builtin.assert:
    that:
      - gnome_shell_version | length > 0
    fail_msg: "Sorry – no GNOME Shell detected… exiting"

- name: Install packages
  ansible.builtin.apt:
    name: "{{ gnome_packages | default([]) }}"
    update_cache: true
    install_recommends: false
    state: present
  become: true
  when: gnome_packages is defined and (gnome_packages | length > 0)

- name: Ensure that target directory exists
  ansible.builtin.file:
    path: "/home/{{ gnome_user }}/.config/{{ gtk_version }}"
    state: directory
  become_user: "{{ gnome_user }}"
  when: gtk_version is defined

- name: Copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ gnome_user }}"
    group: "{{ gnome_user }}"
    mode: 0644
  loop: "{{ gnome_files|default([]) }}"
  loop_control:
    label: "{{ item.src }}"
  tags:
    - files

# -------------------------------------------------------------------
# Fonts
# -------------------------------------------------------------------

- name: Manage fonts
  ansible.builtin.include_tasks:
    file: fonts.yml
  tags:
    - fonts

- name: Manage GNOME Shell extensions
  ansible.builtin.include_tasks:
    file: extensions.yml
  tags:
    - extensions

- name: Modify application settings using gsettings
  ansible.builtin.command:
    cmd: gsettings {{ ('--schemadir ' + item.schemadir) if 'schemadir' in item else '' }} set {{ item.schema }} {{ item.key }} {{ item.value }}
  become_user: "{{ gnome_user }}"
  changed_when: false
  loop: "{{ gnome_gsettings|default([]) }}"
  loop_control:
    label: "{{ item.key }}"
  tags:
    - settings

- name: Install prerequisites for the dconf module
  ansible.builtin.package:
    name: python3-psutil
    state: present
  become: true
  when: gnome_dconf|default(false)

- name: Modify application settings using dconf
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  become_user: "{{ gnome_user }}"
  loop: "{{ gnome_dconf|default([]) }}"
  loop_control:
    label: "{{ item.key }}"
  changed_when: false
  tags:
    - settings
    - dconf
